# fly.toml app configuration file generated for chatbot-portfolio on 2025-07-12T18:32:27-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'chatbot-portfolio'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[http_service.checks]]
interval = "15s"
timeout = "2s"
grace_period = "30s"
method = "get"
path = "/healthz"
protocol = "http"


[[vm]]
  memory = '2048mb'
  cpu_kind = 'shared'
  cpus = 1
